<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Beckhoff.TwinCAT.Ads" Version="7.0.292" />
    <PackageReference Include="Beckhoff.TwinCAT.Ads.Json" Version="7.0.292" />
    <PackageReference Include="Beckhoff.TwinCAT.Ads.TcpRouter" Version="7.0.292" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

</Project>
